### PR TITLE
Dynamic build tools version

### PR DESCRIPTION
**Pull request by ataylorme**

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
In the example-drops-8-composer repository, I put the `BUILD_TOOLS_VERSION` expressions in `test` and `test-2.x` branches. The reason is that this variable is only necessary when testing the Build Tools Plugin itself, and I didn't want to extra expressions migrating down to every customer site that used that repository as a starting template.

This does, however, add the additional burden that the `test` branches must be periodically updated to keep pace with the master branch. This maintenance could, in theory, also be automated.

We could discuss the trade-off between unnecessary cruft for clients vs. extra branches / maintenance for us if anyone has any opinions on it. I'm not firmly set on the way I did it being the best or only way.

**Comment by ataylorme** [comment]
@greg-1-anderson what about a compromise where if `BUILD_TOOLS_VERSION` is undefined we set it to the current stable version (currently `1.x` but can be `2.x` in the future).

**Comment by greg-1-anderson** [comment]
That's how the [example-drops-8-composer circle.yml file works](https://github.com/pantheon-systems/example-drops-8-composer/blob/test/circle.yml#L31). The issue is that this variable isn't needed by clients, and could be removed.

However, if we decide that the extra two-line modification isn't a problem, we could simply dispense with the `test` branches. If that's the way we'd prefer to go, I'll adjust the drops-8 repo to match.

@stevector, do you have a preference?

**Comment by ataylorme** [comment]
Getting quite a few `[error]  cURL error 7: Failed to connect to terminus.pantheon.io port 443: Connection refused (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) ` in the last few days.

Wondering if we should open a Terminus issue.

**Comment by greg-1-anderson** [comment]
It's not a Terminus issue -- but I'm not sure who owns that. The `Connection refused` is interesting; I usually get `no route to host`.

**Comment by ataylorme** [comment]
@greg-1-anderson 

> The issue is that this variable isn't needed by clients, and could be removed.

This is true but I can't think of a scenario where a client would be using `BUILD_TOOLS_VERSION`. We could change it to something even more specific like `TERMINUS_BUILD_TOOLS_PLUGIN_VERSION`.

**Comment by greg-1-anderson** [comment]
@ataylorme I was more concerned about clutter than collision. I don't think we need to make the variable longer.

**Comment by greg-1-anderson** [comment]
OK, keeping straight exactly what version of what project the Terminus Build Tools plugin is using in its test is proving to be non-trivial as we expand to a small number of additional tests. Combining this with the worry that any `test` branch might become out of date, and I think it better to simply define BUILD_TOOLS_VERSION in the `master` branch so that we have fewer things to track.

**Pull request merged**
