### PR TITLE
Update to WordPress 4.8.1

### PR DESCRIPTION
**Pull request by ataylorme**

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
Do we need to update composer.json and composer.lock in these repositories with every release? Would it be better to have `build:project:create` run `composer update` after pulling the site locally?

I suppose it is faster this way.

**Comment by ataylorme** [comment]
I'd rather have folks start with the latest version. Perhaps we can automate this using GitHub's webhoks to kick off a job on CircleCI to run `composer update` and create the pull request. The job can be done via API whenever a new version of `WordPress-Composer` is tagged.

**Comment by greg-1-anderson** [comment]
We'd want this to run when pantheon-systems/WordPress is tagged, yes? This is the sort of thing I wanted to wire up with updatinator.

**Comment by greg-1-anderson** [comment]
Anyway, 👍 on this PR

**Pull request merged**
