### PR TITLE
Move quicksilver-pushback to require and not require-dev

### PR DESCRIPTION
**Pull request by stevector**
Replacing https://github.com/pantheon-systems/example-wordpress-composer/pull/38 with no merge conflicts against master and fewer changes in composer.lock

### CODE REVIEW

**Comment by stevector** [comment]
I'd like to edit the README here too. I'll edit that file in the multidev to see if the pushback works.

**Comment by stevector** [comment]
@greg-1-anderson Can you update the GitHub token for @pantheon-ci-bot here https://circleci.com/gh/pantheon-systems/example-wordpress-composer/edit#env-vars? I think the one currently being used was revoked. And the only place it is used is in Pushback which I'm now trying to test.

**Comment by greg-1-anderson** [comment]
@stevector The GitHub token was used to write the "Created multidev environment" commit comments, so the one in Circle is okay. It looks like the GitHub token being written to the environment via the Terminus secrets plugin (and in fact I confirmed it is there). Also, the quicksilver pushback script is mentioned in the pantheon.yml file. However, the pushback script itself does not appear to have been installed on the Pantheon site.

This repository needs to add:

- [rvtraveller/qs-composer-installer ](https://github.com/pantheon-systems/example-drops-8-composer/blob/master/composer.json#L22)
- [pantheon-systems/quicksilver-pushback](https://github.com/pantheon-systems/example-drops-8-composer/blob/master/composer.json#L35)

These probably both go in the `require` section, not `require-dev`.

**Comment by greg-1-anderson** [comment]
We had talked at one point about having a single Composer project we could require to make a composer-managed Drupal site Pantheon-capable. While we are a ways from making that completely possible, perhaps we should at least choose a name for what we'd like to call it (pantheon-systems/build-tools-runtime?), and then include the projects above from it.

We could, perhaps, also put the test scripts in that project rather than the docker container, and reference them from .circleci/config.yml via the vendor directory. Then we wouldn't need to semver a docker container.

**Comment by stevector** [comment]
> This repository needs to add:
> 
> rvtraveller/qs-composer-installer
> pantheon-systems/quicksilver-pushback

That's what this PR is already doing: moving `pantheon-systems/quicksilver-pushback` from `require-dev` to `require`.

@greg-1-anderson, can you try making a commit in SFTP mode in the resulting multidev while running `terminus workflow:watch?`

**Comment by greg-1-anderson** [comment]
> can you try making a commit in SFTP mode in the resulting multidev while running terminus workflow:watch?

That won't work -- the quicksilver pushback script was not installed to the correct location. I'll see if I can figure out why that happened.

**Comment by stevector** [comment]
It's in the right spot.

```
sftp -o Port=2222 pr-41.46afe9ed-ebf0-44fe-acac-229694bfd8b3@appserver.pr-41.46afe9ed-ebf0-44fe-acac-229694bfd8b3.drush.in
Connected to appserver.pr-41.46afe9ed-ebf0-44fe-acac-229694bfd8b3.drush.in.
sftp> ls code/web/private/scripts/quicksilver/quicksilver-pushback
code/web/private/scripts/quicksilver/quicksilver-pushback/LICENSE                                          code/web/private/scripts/quicksilver/quicksilver-pushback/README.md
code/web/private/scripts/quicksilver/quicksilver-pushback/composer.json                                    code/web/private/scripts/quicksilver/quicksilver-pushback/lean-repo-utils.php
code/web/private/scripts/quicksilver/quicksilver-pushback/push-back-to-github.php
```

I just hadn't invited @pantheon-ci-bot to be a collaborator on the repo. /head-desk.

**Comment by greg-1-anderson** [comment]
Glad you figured that out. I must have made a mistake when I looked for the script in the Pantheon site.

**Comment by ataylorme** [comment]
@stevector I am seeing permission denied 

```
git push git@github.com:pantheon-systems/example-wordpress-composer.git issue-35-quicksilver-pushback-403--take-2
remote: Permission to pantheon-systems/example-wordpress-composer.git denied to pantheon-ci-bot.
fatal: unable to access 'https://REDACTED:x-oauth-basic@github.com/pantheon-systems/example-wordpress-composer.git/': The requested URL returned error: 403
```

**Comment by stevector** [comment]
@ataylorme, could you review (and merge?). I tested this same change on a personal project and it worked.

**Comment by ataylorme** [comment]
@stevector I'm still getting the `403` error (below) in `terminus workflow watch` when testing.

```
git add .
git push git@github.com:pantheon-systems/example-wordpress-composer.git issue-35-quicksilver-pushback-403--take-2
remote: Permission to pantheon-systems/example-wordpress-composer.git denied to pantheon-ci-bot.
fatal: unable to access 'https://REDACTED:x-oauth-basic@github.com/pantheon-systems/example-wordpress-composer.git/': The requested URL returned error: 403
```

I'm hesitant to approve without the pushback working

**Comment by stevector** [comment]
@greg-1-anderson can you sign in as  @pantheon-ci-bot and accept the invite to this repo?

**Comment by stevector** [comment]
Can you try going directly to this URL? @greg-1-anderson @pantheon-ci-bot 
https://github.com/pantheon-systems/example-wordpress-composer/invitations

screen shot 2017-10-11 at 8 44 55 am

**Pull request merged**
