### PR TITLE
Use "-r" instead of "-a" in rsync

### LINKED ISSUE #184: Operation not permitted
I've been doing some tests with the `build:project:create` command using this `example-wordpress-composer` template. However I'm facing an issue on Bitbucket: After pushing some code to master and running my pipelines, when I get to the command:

`rsync -a web/wp/wp-content/mu-plugins/pantheon web/wp/wp-content/mu-plugins/pantheon.php web/wp-content/mu-plugins/`

I get this error:

`rsync: chgrp "/opt/atlassian/pipelines/agent/build/web/wp-content/mu-plugins/pantheon" failed: Operation not permitted (1)`

[Screenshot](https://cl.ly/6cb1e37eaf67)

I'm not sure if it's a bug or something I'm doing wrong.

BTW that command is [here](https://github.com/pantheon-systems/example-wordpress-composer/blob/5a7c8f34c9cbbde5466a5ecde84eae830ae962d1/scripts/composer/cleanup-composer#L7).

What is that command for? Is it required for this template to work with the Bitbucket Pipelines integration with Pantheon?

Thank you.

### PR DESCRIPTION
**Pull request by nelsonamaya82**
This fixes #184 by replacing `-a` flag for `-r` flag in the `rsync` commands (special thanks to @ataylorme).

### CODE REVIEW

**Comment by ataylorme** [comment]
@nelsonamaya82 thanks for the PR! We don't allow tests from forks so I am running them in #186

**Comment by ataylorme** [comment]
If you wanted to open a PR on the Drupal repo as well it is [this line](https://github.com/pantheon-systems/example-drops-8-composer/blob/master/.circleci/config.yml#L141).

**Comment by nelsonamaya82** [comment]
Thanks @ataylorme .

> If you wanted to open a PR on the Drupal repo as well it is [this line](https://github.com/pantheon-systems/example-drops-8-composer/blob/master/.circleci/config.yml#L141).

Sure I'll do. How can I do this to allow tests directly in the PR?

**Comment by ataylorme** [comment]
> How can I do this to allow tests directly in the PR?

You can't. For security reasons tests don't run from PRs as they could expose sensitive environment variables/credentials to anyone who makes a PR.

Once you make a PR I will mirror it in a branch on the repo to run tests

**Comment by ataylorme** [comment]
Tests passed in #186

**Pull request merged**
