### PR TITLE
Use WordHat Directly

### PR DESCRIPTION
**Pull request by ataylorme**
Use WordHat directly, rather than our fork, now that needed changes are merged

### CODE REVIEW

**Comment by ataylorme** [comment]
Tests are passing with WordHat proper. Will be nice to delete my fork!

Looking for a +1 before merging @stevector or @greg-1-anderson

**Comment by greg-1-anderson** [comment]
+1 LGTM Awesome Congratulations   🚢 🚀 💥

**Comment by ataylorme** [comment]
Big shout out and thanks to @paulgibbs and WordHat for making our Behat testing much easier!

**Comment by paulgibbs** [comment]
Love Pantheon! Keep up the good work!

**Comment by paulgibbs** [comment]
@ataylorme do you want me to tag a new version of wordhat so you can pin to that instead of master? I'm making no long-term promises about the stability of master.

**Comment by paulgibbs** [comment]
Most of the work for v1.0 is website/docs, and probably another dozen step definitions or so. I don't think we're planning any more breaking changes. It's probably OK to leave. I'll tag a build later, anyway.

**Comment by paulgibbs** [comment]
Sorry I forgot to do this, I've just tagged 0.7.1 from https://github.com/paulgibbs/behat-wordpress-extension/commit/bf7650859898755071f909a0f5d29684c8d44633 which was the merge commit for https://github.com/paulgibbs/behat-wordpress-extension/pull/116 which I think is the change that prompted you @ataylorme to open this URL.

Master, so far, has documentation changes, as well as bumping the minimum required WP-CLI to 1.3.0 because WordHat needs https://github.com/wp-cli/wp-cli/pull/4207 to prevent problems running WordHat with WP-CLI over SSH (so if in your docs you have people install WP-CLI manually, you should tell them 0.13.0 or newer).

**Pull request merged**
