### PR TITLE
Use custom Behat feature for WordPress login

### PR DESCRIPTION
**Pull request by ataylorme**
It turns out the Behat issue was not with GitLab but with the WordHat. I posted my login woes in their Slack instance and got this reply

> The log-in step has been always troublesome. If you look at the browser at the failing test, is it doing something like entering the username but not the password - something like that?
> If it is it is probably the project’s oldest bug and several of us have been unable to reliably fix it.

So I spend the day writing custom features to make login more reliable and have some Pantheon specific items as well.

In addition, I think showing off custom contexts will be helpful to people learning Behat.

`PantheonContext.php` might need some cleanup as it is functional (all tests pass locally, on CircleCI, and on GitLab) but not pretty.

### CODE REVIEW

**Comment by ataylorme** [comment]
Passing Behat tests with this setup on GitLab can be found [here](https://gitlab.com/ataylorme/ataylor-gitlab-test-11/-/jobs/165537649)

The passing Behat tests are in [CircleCI job 1102](https://circleci.com/gh/pantheon-systems/example-wordpress-composer/1102)

**Comment by ataylorme** [comment]
Please do not merge this as the maintainers of WordHat are open to upstream changes. I want to see if we can get some of the improvements into WordHat and keep the custom features here more directly related to Pantheon (e.g. clear Pantheon cache).

**Comment by greg-1-anderson** [comment]
OK. Can we work off of a branch for BT-6, or is this PR even necessary to make progress? BT-7 is about done (in AC review).

**Comment by ataylorme** [comment]
My upstream PR got merged and WordHat `3.1.1` was released. [Tests are green](https://circleci.com/gh/pantheon-systems/example-wordpress-composer/1191) using the new WordHat version instead of my fork.

@greg-1-anderson I removed work-in-progress and this is ready for review.

**Pull request merged**
