### PR TITLE
BT-7: Support GitLab CI

### PR DESCRIPTION
**Pull request by ataylorme**

### CODE REVIEW

**Comment by ataylorme** [comment]
After CircleCI passes with more generic bash variables I will work on a `.gitlab-ci.yml` that uses the same scripts.

@greg-1-anderson what do you think about moving the bash scripts to a directory other than `.circleci`?

**Comment by rvtraveller** [comment]
I like the direction this is going and am a fan of moving the scripts to `.ci` instead of `.circleci`. Presumably in the future there may be other CI providers as well.

One thing to consider, since this is a "template" people are using, is do we want to force the asset compilation, testing, etc on them by default? We could easily include those jobs but have variables for them that control whether they run or not -- https://docs.gitlab.com/ee/ci/yaml/#onlyvariables-and-exceptvariables. If we go that route, then we could decide that we are defaulting those variables to on (or off) and in future iterations add flags to Build Tools in future iterations that allow for those variables to by command line flag at project creation.

**Comment by ataylorme** [comment]
> If we go that route, then we could decide that we are defaulting those variables to on (or off) and in future iterations add flags to Build Tools in future iterations that allow for those variables to by command line flag at project creation.

I am -1 on building flags to control which Gitlab jobs run into build tools. Build tools is meant to scaffold an opinionated example, which can be tweaked to suit the needs of the project.

Build tools can also create a new project from any git repository, not just our examples. 

In my opinion, if an agency wishes to have a different default setup they should fork `example-wordpress-composer` and modify the CI files to fit their needs, then create new projects from their custom setup.

**Comment by ataylorme** [comment]
@greg-1-anderson passing tests on a repo created from this branch [can be seen here](https://gitlab.com/ataylorme/ataylor-gitlab-test-09/pipelines/48281473).

Note that I had to manually pull this branch (see [this comment](https://github.com/pantheon-systems/terminus-build-tools-plugin/pull/110#issuecomment-465345952)) but once I did things were okay.

**Comment by greg-1-anderson** [comment]
@ataylorme I get a 404 on that first url. Permissions?

**Comment by ataylorme** [comment]
Sorry - you should be added now

**Pull request merged**
